<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>03-downmusic</title>
    <style>
        table, tr, th, td{border:1px solid black; border-collapse:collapse; text-align: center;}
        #desc{font-weight: bold; font-size:14pt;}
        .estado{color:ForestGreen;};
    </style>
    <!-- <link rel="stylesheet" href="../bootstrap.min.css"> -->
</head>
<body>


 <h1 class="text-center"> REALIZAR PEDIDO </h1>
            <form id="product-form" name="formulario" action="03-downmusic.php" method="post" class="card-body">
                <div>Cancion:
                    <select name="track">
                        <?php foreach($tracks as $track) : ?>
                            <option> <?php echo $track ?> </option>
                        <?php endforeach; ?>
                    </select>
                    <br><br>
                    
                </div>
                 
                <div>
                    <br>
                    <input type="submit" value="Comprar Canciones" name="comprar">
                    <input type="submit" value="Agregar a la Cesta" name="agregar">
                    <input type="submit" value="Limpiar la Cesta" name="limpiar">
                </div>
            </form>    
        <br>


</body>
</html>
